module.exports = {
    instagram: {
        bot: {
            user: '',
            pass: '',
            commentFrequency: 8,
            followFrequency: 100,
            postsPerTag: 100,
            tags: [
                'mensfashion',
                'mensstyle',
                'menswear',
                'streetfashion',
                'fashion',
                'outfit',
                'clothing',
                'instafashion',
                'model',
                'fashionporn',
                'stylish',
                'style',
                'menstyle',
                'mensfashionblog',
                'mensfashiontips',
                'mensfashionpost',
            ],
            comments: [
                'You\'re Inspiring!',
                'First Rate Work!',
                'Keep Up The Good Work! :)',
                'Great pics, as always.',
                'You are so creative!',
                'Exceptional',
                'Very professional ',
                'Magnificent',
                'Superb!',
            ],
            post_comment: '.\n.\n.\n.\n.\n#mensfashion #mensstyle #mensflyfashion #menswear #dope #swag #swagger #street #streetfashion #fashion #outfit #clothing #instafashion #model #fashionporn #stylish #style #menstyle #motivation #follows4follow #follow4follow #beautiful #igdaily #mensfashionblog #mensfashiontips #mensfashionpost',
        },
    },
};
